### ISSUE TITLE
[Bug] No SD card access

### ISSUE THREAD

**Issue by eson57** [sailfishos-applications/flowplayer#26]
**SailfishOS VERSION**:  4.5.0.24
<br />**HARDWARE**:  Sony Xperia 10 III
<br />**FlowPlayer VERSION**:  Flowplayer says 0.1-9, OpenRepos says 0.3.0-rc1   ;-)
<br />

#### BUG DESCRIPTION
The file selector is trapped inside the home directory, so no SD card access.

#### STEPS TO REPRODUCE
Start Flowplayer, go to Settings/Manage folders/Add folder (pulley menu)/. Hit the up arrow and try to browse your SD card.

#### ADDITIONAL INFORMATION
I'm not really sure this is a bug or a feature request. I can't remember if it ever was possible to use SD card.
There is access to other directory's that I think is irrelevant though. See screen below.

![copy-25Screenshot_20231206_001](https://github.com/sailfishos-applications/flowplayer/assets/2996154/96969d20-7e7a-44a3-9c4d-539d01c11813)

**Comment by branja6** [comment]
I'm not having the issue.
![Screenshot_20231206_001](https://github.com/sailfishos-applications/flowplayer/assets/71647226/31395741-0e4c-429e-a79e-d6d27c6d908c)

**Comment by Olf0** [comment]
@branja6, thank you very much for your comment.

@eson57, do you have an idea what may be different on your Xperia10III@SFOS4.5.0.24?

**Comment by Olf0** [comment]
> Mine was on /run/media/defaultuser/etc

Yes, this is where the additional storage devices (SD card or USB-attached storage) is mounted (IIRC since SFOS 2.2.1):
`/run/media/<username>/<UUID>/`

**Comment by eson57** [comment]
Yes, issue resolved, thank you! I had to hit the up arrow one more time, and it was _not_ that obvious.
