### ISSUE TITLE
[Bug] Remaining hardcoded paths to `/home/nemo`

### ISSUE THREAD

**Issue by Olf0** [sailfishos-applications/flowplayer#47]
Still a couple of hardcoded paths to `/home/nemo` remain, see https://github.com/search?q=repo%3Asailfishos-applications%2Fflowplayer+%22/nemo%22&type=code
This also explains, why `/home/nemo/.config/cepiperez/…` is still used by v0.3.1-rcX.

IOW, unfortunately PR #21 did not catch all occurrences of `/home/nemo`.

P.S.: I have no idea, if these `x-nemo` matches are still correct: https://github.com/search?q=repo%3Asailfishos-applications%2Fflowplayer+%22x-nemo%22&type=code

**Comment by dcaliste** [comment]
For the `X-Nemo-Application-Type` in the desktop file, it seems correct to me. At least in a non sandboxing context. The Ofono log viewer from Slava is using the same layout for its desktop file.

**Comment by dcaliste** [comment]
Ah, by the way, what do you mean by "This also explains, why `/home/nemo/.config/cepiperez/…` is still used by v0.3.1-rcX." ? Do you have some part of the program that try to access this path and write a warning in the console ? Or some user reporting having access to this directory ?

**Comment by Olf0** [comment]
> Or some user reporting having access to this directory ?

Yes, [this statement](https://github.com/sailfishos-applications/flowplayer/blob/devel/migrating-to-v0.3.x.md) made me search: "For some reason the active configuration file is now in cepiperez and the active database in flowplayer."

**Comment by Olf0** [comment]
> For the `X-Nemo-Application-Type` in the desktop file, it seems correct to me.

Sure.  Sorry, I was too brief, I meant these statements in [`extras/Lockscreen.qml`](https://github.com/sailfishos-applications/flowplayer/blob/34ee039f1e24b10be5803ce01a46f72afe9448a7/extras/Lockscreen.qml#L224):
`"comparator": "!match",`
`"value": "^x-nemo.system-update"`

**Comment by dcaliste** [comment]
> "For some reason the active configuration file is now in cepiperez and the active database in flowplayer."

Good point. Indeed, I changed the path of the database, from a hardcoded `/home/nemo/.config/cepiperez/` to `QStandardLocation::AppConfigLocation`, which resolves into `~/.config/flowplayer/flowplayer/` (the organisation name is `flowplayer` and the application name is `flowplayer` too). But doing so, I didn't touch any of the `QSettings`. In the code, all settings are still accessed by `QSettings settings("cepiperez", "flowplayer");` which means that the organisation name is `cepiperez`. That's clearly inconsistent.

There are three possibilities:
1. change `QSettings` to use `flowplayer` as organisation name,
2. change the organisation name to `cepiperez` (see `src/FlowPlayer.cpp#31`),
3. don't touch anything.

The two first suggestions will disturb the users who already migrate. Either they will have to move the config or the database. The last proposition keeps the status quo. The migration can also be done programatically by copying behind the scene one or the other file to the new location. What do you suggest ?

> I meant these statements containing `x-nemo.system-update in extras/Lockscreen.qml`

My bad, I wrote about `LockScreen.qml` file in #48 without making a note here. I think that this file was an attempt to modify the Jolla Lipstick lock screen. Maybe at a moment when patchmanager was not available. Anyway, the base for this file seems to be ancient and I have trouble to find matchs with the current `LockScreen.qml` file from 4.5.0. I think it's safer to ignore this file at the moment.

**Comment by Olf0** [comment]
> What do you suggest ?

Please let us do it "right", whatever we define as right.  All v0.3.x releases have been marked as release candidates (I should have marked them as betas in hindsight), so things may change; still I sure would denote that in the release notes and teh forum thread.

Hence I do not like your point 3.  I would suggest to choose between:
a. Org name `cepiperez` for compatibility
b. Org name `flowplayer` for compatibility for the ones who have already migrated.
c. Org name `sailfishos-applications` to reflect the GitHub-organisation under which FlowPlayer is developed.

**Comment by dcaliste** [comment]
Thanks @Olf0 for your remarks. I should have opened this discussion earlier...

Anyway, I would prefer c. myself. Not a huge fan of organisation == application names (actually I find it silly to impose this two level structure that I find a bit arbitrary, but well it was chosen and adopted by Freedesktop as far as I know, so let's follow common standards).

I've created #50 to follow this discussion in a dedicated issue. I've copy-pasted part of our discussion.
